### ISSUE TITLE
Missing binary file detection

### ISSUE THREAD

**Issue by marcomarinodev** [Doriandarko/RepoToTextForLLMs#1]
Hi there, 
I was using it for a c++ project and in the repo there was a binary output file that was not declared in the .gitignore.
It would be interesting to have a check to ignore binary files.

The solution would be simple, something like this:

```python
def is_binary_file_with_mimetype(file_path):
    mime_type, _ = mimetypes.guess_type(file_path)
    if mime_type is not None
        return mime_type.startswith('text/') == False
    return False
```

I could open a PR if you're interested.

Thank you.

**Comment by Doriandarko** [comment]
On default it should already avoid any type of binary file, what was the file type?

**Comment by marcomarinodev** [comment]
The file has no extension, it's just an out file.

https://github.com/marcomarinodev/parallel-huffman/blob/main/output
